### ISSUE TITLE
When on tags tab, there is blank extra space beneath.

### ISSUE THREAD

**Issue by Kav91** [newrelic/nr1-container-explorer#10]
Only occurs when on the tags tab, "processes" and "charts" tabs are okay.

![image](https://user-images.githubusercontent.com/13043208/64671334-704b7400-d4ab-11e9-9940-68531620f717.png)

**Comment by danielgolden** [comment]
I know what the problem is, so I'll submit a PR that includes this fix soon.

**Comment by danielgolden** [comment]
Fixed in #19
