### ISSUE TITLE
Modify the explorer details for services / related entitities w/in a container

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-container-explorer#23]
The Explorer details needs to list:
- name of the Service, linked to the openStackedEntity overview
- link to reorient the explorer to that Entity

Consider using icons/tooltips vs. repeated text.

<img width="381" alt="Screen Shot 2020-01-13 at 9 03 23 PM" src="https://user-images.githubusercontent.com/929261/72307460-592eb580-3648-11ea-89bd-dd60b767c7e7.png">

cc: @cirne

**Comment by danielgolden** [comment]
If I'm understanding this issue correctly, #21 from @devfreddy may take care of each of these points:

<img width="427" alt="Captura de Pantalla 2020-01-14 a la(s) 7 30 27 a  m" src="https://user-images.githubusercontent.com/812989/72344654-c4f03d00-369f-11ea-9f3e-4a8ce6ea1934.png">

**Comment by cirne** [comment]
Thanks! Let me know when an updated version is deployed to staging!

**Comment by devfreddy** [comment]
Re-opening - we're incorrectly utilizing _the same_ icon regardless of Entity Type. We should make it dynamic based on Entity Type.

**Comment by devfreddy** [comment]
This was completed here - 343af174e138c8186b8460cdfe413d5985fe417a
