### ISSUE TITLE
After you drill down on a set of Containers, there's no intuitive way to reset container filters

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-container-explorer#29]
- Choose a container
- Drill down into some details

How do I reset to see everything? The choice isn't obvious. Where in the UI should this go?

**Comment by danielgolden** [comment]
I think adding it into the options bar/header is the best option:

<img width="919" alt="Captura de Pantalla 2020-01-29 a la(s) 8 35 52 a  m" src="https://user-images.githubusercontent.com/812989/73361164-610a6e80-4272-11ea-8128-4b21dffd2f63.png">

PR incoming...
