### ISSUE TITLE
Errors out on clicking any single host from the main page

### ISSUE THREAD

**Issue by kumarsb3** [newrelic/nr1-container-explorer#62]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

Once we select an account, it loads the main page with all hosts/containers. When we click any one of the container, we're getting a "Oops something went wrong" error. 

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

Once we select an account from dropdown, it loads the main page with all hosts/containers. When we click any one of the container, we're getting a "Oops something went wrong" error. 

## Expected Behaviour

Clicking on any of the container/host should display individual node details and related graphs.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used:
* Browser name and version: Chrome Version 87.0.4280.141
* Operating System and version: MacOS Mojave 10.14.6

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by aswanson-nr** [comment]
I ran into the same issue on my end, clicking on any of the containers appears to crash the app.
Here is a screenshot of the error, there are multiple, but I think the last one is directly related.
<img width="1775" alt="Screen Shot 2021-03-31 at 3 17 06 PM" src="https://user-images.githubusercontent.com/70179303/113218497-742d1b80-9234-11eb-9d75-b2173c3e87f2.png">
